###########
# Local test workflow to reproduce build failures
# Skips Docker Hub login and push operations
###########

name: Docker Image CI - Local Test

on:
  push:
    paths:
      - "release-versions/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current repository
        uses: actions/checkout@v1
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(cat release-versions/n8n-latest.txt)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - run: cp default-requirements.txt images/n8n/requirements.txt
      - name: Build (default => alpine) - LOCAL TEST
        uses: docker/build-push-action@v2
        with:
          context: ./images/n8n
          build-args: |
            N8N_VERSION=${{steps.vars.outputs.tag}}
          platforms: linux/amd64
          push: false # Skip push for local testing
          tags: |
            local-test/n8n-python:${{ steps.vars.outputs.tag }}
            local-test/n8n-python:latest
